### ISSUE TITLE
Remove golang.org/x/net replace directive

### ISSUE THREAD

**Issue by acrmp** [cloudfoundry/otel-collector-release#17]
In #16 we bumped golang.org/x/net with a replace directive.

We should remember to remove this to avoid accidentally pinning the version back.

**Comment by acosta11** [comment]
Plan to remove the replace directive in #28 as part of the otel dependency bump.

**Comment by acrmp** [comment]
The replace was removed in [0bf0af78](https://github.com/cloudfoundry/otel-collector-release/commit/0bf0af78fb9ee0e90083381c26d3d0124b03f991#diff-be61e6828992abe89e87a8a2fc70c929366aded36e91d23c581e471d31267862).
