### ISSUE TITLE
Feature: automatically configure `memory_limiter` and `GOMEMLIMIT`

### ISSUE THREAD

**Issue by oppegard** [cloudfoundry/otel-collector-release#35]
The `memory_limiter` processor has the following guidance under [Best Practices](https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor#best-practices):

> It is highly recommended to configure the `GOMEMLIMIT` [environment variable](https://pkg.go.dev/runtime#hdr-Environment_Variables) as well as the `memory_limiter` processor on every collector. `GOMEMLIMIT` should be set to 80% of the hard memory limit of your collector. For the `memory_limiter` processor, the best practice is to add it as the first processor in a pipeline. This is to ensure that backpressure can be sent to applicable receivers and minimize the likelihood of dropped data when the `memory_limiter` gets triggered.

This guidance is implemented in the official Helm chart for the OTel Collector:
- https://github.com/open-telemetry/opentelemetry-helm-charts/blob/8e489da14e034a66b23b0fc8b80cd1a82af21b74/charts/opentelemetry-collector/templates/_config.tpl#L21
- https://github.com/open-telemetry/opentelemetry-helm-charts/blob/8e489da14e034a66b23b0fc8b80cd1a82af21b74/charts/opentelemetry-collector/templates/_config.tpl#L4-L13
- https://github.com/open-telemetry/opentelemetry-helm-charts/blob/8e489da14e034a66b23b0fc8b80cd1a82af21b74/charts/opentelemetry-collector/values.yaml#L289-L292

We could explore doing something similar, potentially substituting their use of K8s' `resources.limits.memory` with BPM's `limits.memory`: https://github.com/cloudfoundry/bpm-release/blob/master/docs/config.md#limits-schema.

The UX for this feature would be a new Job property of something like `memory` that allows an operator to specify the maximum amount of memory the OTel Collector process should use. Based on that, we could:
1. Set BPM's `limits.memory`.
2. Configure `GOMEMLIMIT` to 80% of `limits.memory`.
3. Configure the `memory_limiter` processor if the operator hasn't already done it via the Job's `config` [property](https://github.com/cloudfoundry/otel-collector-release/blob/75ff4cf917e2cd2acce9a9f32b801bba15cfbb1b/jobs/otel-collector/spec#L20) (similar to how the Helm chart allows overriding the auto-configuration).

We would want to see if BPM implements `limits.memory` via cgroups and in a way that is compatible for the `memory_limiter` processor's `limit_percentage` and `spike_limit_percentage` [config options](https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor#configuration). Otherwise, we would need to use the non-percentage config options and manually calculate the values.

**Comment by ctlong** [comment]
Implemented (1) and (2) in #43, thanks @oppegard! We're somewhat reticent to implement (3) right now, as it seems a little heavy-handed.

Closing this as completed for now.
